# Generated by Django 5.2.8 on 2025-11-18 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_zona_barrido', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_sector', models.IntegerField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('residuos_kg', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionOptima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=20)),
                ('costo_distancia_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carga_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('camion_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver_app.camion')),
                ('ruta_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver_app.ruta')),
            ],
        ),
    ]
